URL = None,
CLIENT_ID = None,
CLIENT_SECRET = None,
USERNAME = None,
PASSWORD = None,
GRANT_TYPE = None,
ACCESS_TOKEN = None,

CFG = {
    "URL": URL,
    "CLIENT_ID": CLIENT_ID,
    "CLIENT_SECRET": CLIENT_SECRET,
    "USERNAME": USERNAME,
    "PASSWORD": PASSWORD,
    "GRANT_TYPE": GRANT_TYPE,
    "ACCESS_TOKEN": ACCESS_TOKEN,
}
